---
- hosts: all
  become: yes
  tasks: 
  - name: "update && install tomcat8"
    apt:
      name: tomcat8
      update_cache: yes
      state: present
  - name: "downlod jenkins war"
    get_url: 
      url: https://updates.jenkins-ci.org/download/war/2.179/jenkins.war
      dest: /var/lib/tomcat8/webapps/jenkins.war
  - name: "service restart"
    service:
      name: tomcat8
      state: restarted
  

